# Generated by Django 6.0.2 on 2026-05-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=200, verbose_name='Cliente o Proveedor')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yo_debo', models.BooleanField(default=False, verbose_name='¿Es una deuda mía?')),
                ('fecha_limite', models.DateField(verbose_name='Fecha de Pago')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso (+)'), ('GASTO', 'Gasto (-)')], max_length=7)),
                ('descripcion', models.TextField(verbose_name='Concepto (Ej. Renta, Pago Proveedor)')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cantidad en Existencia'),
        ),
    ]
