# Generated by Django 4.2.19 on 2026-05-03 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_deuda_movimientocaja_producto_costo_producto_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deuda",
            name="saldo_pendiente",
        ),
        migrations.CreateModel(
            name="Abono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "deuda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonos",
                        to="tienda.deuda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abono",
                "verbose_name_plural": "Abonos",
            },
        ),
    ]
