# Generated by Django 6.0.4 on 2026-05-05 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_deuda_saldo_pendiente_abono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abono',
            options={'ordering': ['-fecha'], 'verbose_name': 'Abono', 'verbose_name_plural': 'Abonos'},
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Abono'),
        ),
    ]
