# Generated by Django 6.0.5 on 2026-05-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_abono_options_alter_abono_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abono',
            options={'verbose_name': 'Abono', 'verbose_name_plural': 'Abonos'},
        ),
        migrations.AlterModelOptions(
            name='movimientocaja',
            options={'ordering': ['-monto'], 'verbose_name': 'Movimiento de Caja', 'verbose_name_plural': 'Movimientos de Caja'},
        ),
        migrations.RemoveField(
            model_name='deuda',
            name='yo_debo',
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
