# Generated by Django 6.0.5 on 2026-05-06 00:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_abono_options_alter_movimientocaja_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abono',
            options={'ordering': ['-fecha'], 'verbose_name': 'Abono', 'verbose_name_plural': 'Abonos'},
        ),
        migrations.AlterModelOptions(
            name='deuda',
            options={'ordering': ['-monto_total'], 'verbose_name': 'Deuda', 'verbose_name_plural': 'Deudas'},
        ),
        migrations.AlterModelOptions(
            name='movimientocaja',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Caja', 'verbose_name_plural': 'Movimientos de Caja'},
        ),
        migrations.AddField(
            model_name='deuda',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
