# Generated by Django 6.0.5 on 2026-05-06 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_abono_options_alter_deuda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deuda',
            options={'verbose_name': 'Deuda', 'verbose_name_plural': 'Deudas'},
        ),
        migrations.AlterModelOptions(
            name='movimientocaja',
            options={'ordering': ['-monto'], 'verbose_name': 'Movimiento de Caja', 'verbose_name_plural': 'Movimientos de Caja'},
        ),
        migrations.RemoveField(
            model_name='deuda',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Abono'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
