# Generated by Django 6.0.5 on 2026-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_deuda_options_alter_movimientocaja_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deuda',
            options={'verbose_name': 'Deuda', 'verbose_name_plural': 'Administracion De Deudas'},
        ),
        migrations.AddField(
            model_name='deuda',
            name='yo_debo',
            field=models.BooleanField(default=False, verbose_name='¿Es deuda mía?'),
        ),
    ]
