# Generated by Django 6.0.5 on 2026-05-09 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_venta_alter_deuda_persona_ventadetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deuda',
            options={'verbose_name': 'Deuda', 'verbose_name_plural': 'Administración De Deudas'},
        ),
        migrations.RemoveField(
            model_name='deuda',
            name='fecha_limite',
        ),
        migrations.AddField(
            model_name='abono',
            name='pagado',
            field=models.BooleanField(default=True, verbose_name='¿Pagado?'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='cantidad_pagos',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de Plazos'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='periodicidad_dias',
            field=models.PositiveIntegerField(default=0, verbose_name='Cada cuántos días'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago/Programada'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='persona',
            field=models.CharField(max_length=200, verbose_name='Proveedor / Acreedor'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='yo_debo',
            field=models.BooleanField(default=True, verbose_name='¿Es deuda mía?'),
        ),
    ]
