# Generated by Django 6.0.5 on 2026-05-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_deuda_options_remove_deuda_fecha_limite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abono',
            options={'ordering': ['fecha'], 'verbose_name': 'Abono', 'verbose_name_plural': 'Abonos'},
        ),
        migrations.AddField(
            model_name='deuda',
            name='monto_por_pago',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Monto por cada pago'),
        ),
    ]
