# Generated by Django 6.0.5 on 2026-05-13 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_abono_options_deuda_monto_por_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'Ticket de Venta', 'verbose_name_plural': 'Historial de Tickets (Cajas)'},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='notas',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.CharField(default='Cliente De Prueba', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(default='00000', max_length=20, unique=True, verbose_name='Folio Ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(default='TRANSFERENCIA', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='monto_por_pago',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Monto x c/pago'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='persona',
            field=models.CharField(max_length=200, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.venta')),
            ],
        ),
        migrations.DeleteModel(
            name='VentaDetalle',
        ),
    ]
