# Generated by Django 6.0.5 on 2026-05-13 01:47

import django.db.models.deletion
import tienda.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_venta_options_remove_venta_metodo_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='qr_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='folio',
            field=models.CharField(default=tienda.models.generar_folio, max_length=20, unique=True, verbose_name='Folio Ticket'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='TRANSFERENCIA', max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
