# Generated by Django 6.0.5 on 2026-05-14 14:50

import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_detalleventa_producto_venta_qr_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.CharField(default='Venta Mostrador', max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='folio',
            field=models.CharField(default=tienda.models.generar_folio, editable=False, max_length=30, unique=True, verbose_name='Folio Ticket'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADO PAGO', 'Mercado Pago'), ('PAYPAL', 'PayPal'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=50),
        ),
    ]
