# Generated by Django 6.0.5 on 2026-05-24 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_venta_cliente_alter_venta_folio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abono',
            options={'ordering': ['fecha', '-id'], 'verbose_name': 'Abono', 'verbose_name_plural': 'Historial General de Abonos'},
        ),
        migrations.AlterModelOptions(
            name='deuda',
            options={'verbose_name': 'Cuenta por Pagar (Proveedor)', 'verbose_name_plural': '1. Cuentas por Pagar (Proveedores)'},
        ),
        migrations.RemoveField(
            model_name='deuda',
            name='yo_debo',
        ),
        migrations.AlterField(
            model_name='abono',
            name='deuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='tienda.deuda'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='persona',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADO PAGO', 'Mercado Pago'), ('PAYPAL', 'PayPal'), ('TARJETA', 'Tarjeta'), ('CREDITO', 'Crédito')], default='EFECTIVO', max_length=50),
        ),
        migrations.CreateModel(
            name='VentaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=200)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('cantidad_pagos', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Plazos')),
                ('periodicidad_dias', models.PositiveIntegerField(default=0, verbose_name='Cada cuántos días')),
                ('monto_por_pago', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Monto x c/pago')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credito_asignado', to='tienda.venta')),
            ],
            options={
                'verbose_name': 'Venta a Crédito (Cliente)',
                'verbose_name_plural': '2. Ventas a Crédito (Clientes)',
            },
        ),
        migrations.AddField(
            model_name='abono',
            name='venta_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='tienda.ventacredito'),
        ),
    ]
