# Generated by Django 6.0.5 on 2026-05-31 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_alter_abono_options_alter_deuda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deuda',
            options={'verbose_name': 'Cuenta por Pagar)', 'verbose_name_plural': 'Cuentas por Pagar'},
        ),
        migrations.AlterModelOptions(
            name='ventacredito',
            options={'verbose_name': 'Venta a Crédito', 'verbose_name_plural': 'Ventas a Crédito'},
        ),
    ]
